export const images = {
  login: {
    verify_code: require('./images/login/verify_code.png'),
    phone: require('./images/login/phone.png'),
    formbg: require('./images/login/formbg.png'),
    headerbg: require('./images/login/headerbg.png'),
    login_logo: require('./images/login/loginLogo.png'),
    user: require("./images/login/user.png"),
    email: require("./images/login/email.png")
  },
  common: {
    avatar: require('./images/common/avatar.png'),
    comment: require('./images/common/comment.png'),
    eye: require('./images/common/eye.png'),
    guan: require('./images/common/guan.png'),
    search: require('./images/common/search.png'),
    search2: require('./images/common/search2.png'),
    zan: require('./images/common/zan.png'),
    share: require('./images/common/share.png'),
    video_play: require('./images/common/video_play.png'),
    download: require('./images/common/download.png'),
    arrow_down: require('./images/common/arrow_down.png'),
    arrow_up: require('./images/common/arrow_up.png'),
    plus_black: require('./images/common/plus_black.png'),
    plus_white: require('./images/common/plus_white.png'),
    club_empty: require('./images/common/club_empty.png'),
    group: require('./images/common/group.png'),
    arrow_right: require('./images/common/arrow_right.png'),
    location: require('./images/common/location.png'),
    cate: require('./images/common/cate.png'),
    time: require('./images/common/time.png'),
    contact: require('./images/common/contact.png'),
    contactWhite: require('./images/common/contactWhite.png'),
    service: require('./images/common/service.png'),
    inbox: require('./images/common/inbox.png'),
    add_friend: require('./images/common/add_friend.png'),
    arrow_right2: require('./images/common/arrow_right2.png'),
    arrow_right3: require('./images/common/arrow_right3.png'),
    about_logo: require('./images/common/about_logo.png'),
    list: require('./images/common/list.png'),
    video: require('./images/common/video.png'),
    camera: require('./images/common/camera.png'),
    close: require('./images/common/close.png'),
    switch_camera: require('./images/common/switch_camera.png'),
    shutter: require('./images/common/shutter.png'),
    video_recording: require('./images/common/video_recording.png'),
    star_active: require('./images/common/star_active.png'),
    zan_active: require('./images/common/zan_active.png'),
    write: require('./images/common/write.png'),
    star: require('./images/common/star.png'),
    consult: require('./images/common/consult.png'),
    contest_level: require('./images/common/contest_level.png'),
    submit_success: require('./images/common/submit_success.png'),
    report_icon: require('./images/common/report_icon.png'),
    delete: require('./images/common/delete.png'),
    btn_switch_point: require('./images/common/btn_switch_point.png'),
    warning: require('./images/common/warning.png'),
    infor_icon: require("./images/common/infor.png"),
    point_icon: require("./images/common/point.png"),
    redPoint: require("./images/common/redPoint.png"),
    arrow: require("./images/common/arrow.png"),
    follow: require("./images/common/follow.png"),
    money: require("./images/common/money.png"),
    Vector: require("./images/common/Vector.png"),
    navi: require("./images/common/navi.png"),
    report: require("./images/common/report.png"),
    dynamicInfor: require("./images/common/dynamicInfor.png"),
    publish: require("./images/common/publish.png"),
    version: require("./images/common/version.png"),
    inforModal: require("./images/common/inforModal.png"),
    rule: require("./images/common/rule.png"),
    check: require("./images/common/check.png"),
    register_form: require("./images/common/register_form.png"),
    register_success: require("./images/common/register_success.png"),
    recommend: require("./images/common/recommend.png"),
    wallet: require("./images/common/wallet.png"),
    payment: require("./images/common/payment.png"),
    honor: require("./images/common/honor.png")
  },
  share: {
    friend_circle_icon: require('./images/share/friend_circle_icon.png'),
    wx_icon: require('./images/share/wx_icon.png'),
  },
  submenu: {
    caipan: require('./images/submenu/caipan.png'),
    chengji: require('./images/submenu/chengji.png'),
    jiaoguan: require('./images/submenu/jiaoguan.png'),
    saishi: require('./images/submenu/saishi.png'),
    peixun: require('./images/submenu/peixun.png'),
  },
  home: {
    dongtai: require('./images/home/dongtai.png'),
    banner: require('./images/home/banner.png'),
    tab_decor: require('./images/home/tab_decor.png'),
    back: require('./images/home/back.png'),
  },
  tab: {
    club: require('./images/tab/club.png'),
    club_active: require('./images/tab/club_active.png'),
    home: require('./images/tab/home.png'),
    home_active: require('./images/tab/home_active.png'),
    msg: require('./images/tab/msg.png'),
    msg_active: require('./images/tab/msg_active.png'),
    my: require('./images/tab/my.png'),
    my_active: require('./images/tab/my_active.png'),
    push: require('./images/tab/push.png'),
    member: require("./images/tab/member.png"),
    member_active: require("./images/tab/member_active.png"),
    shopping: require("./images/tab/shopping.png"),
    shopping_active: require("./images/tab/shopping_active.png"),
  },
  mine: {
    headerbg: require('./images/mine/headerbg.png'),
    minebg: require('./images/mine/minebg.png'),
    saishi: require('./images/mine/saishi.png'),
    peixun: require('./images/mine/peixun.png'),
    paiming: require('./images/mine/paiming.png'),
    jifen: require('./images/mine/jifen.png'),
    tongyong: require('./images/mine/tongyong.png'),
    shangcheng: require('./images/mine/shangcheng.png'),
    club: require('./images/mine/club.png'),
    shouchang: require('./images/mine/shouchang.png'),
    shidan: require('./images/mine/shidan.png'),
    qiqiang: require('./images/mine/qiqiang.png'),
    caipan: require('./images/mine/caipan.png'),
    guojicaipan: require('./images/mine/guojicaipan.png'),
    jiaoguan: require('./images/mine/jiaoguan.png'),
    huizhang: require('./images/mine/huizhang.png'),
    cup: require('./images/mine/cup.png'),
    zhaoshang: require('./images/mine/zhaoshang.png'),
    auth_bg: require('./images/mine/auth_bg.png'),
    auth_bg_1: require("./images/mine/auth_bg_1.png"),
    auth_bg_2: require("./images/mine/auth_bg_2.png"),
    auditing: require('./images/mine/auditing.png'),
    post_pass: require('./images/mine/post_pass.png'),
    post_reject: require('./images/mine/post_reject.png'),
    post_review: require('./images/mine/post_review.png'),
    reward: require('./images/mine/reward.png'),
    reward1: require('./images/mine/reward1.png'),
    cert_dt: require('./images/mine/cert_dt.png'),
    city: require('./images/mine/city.png'),
    clubs: require('./images/mine/clubs.png'),
    en_name: require('./images/mine/en_name.png'),
    name: require('./images/mine/name.png'),
    vip: require('./images/mine/vip.png'),
    email: require('./images/mine/email.png'),
    vipNumber: require('./images/mine/vipNumber.png'),
    club2: require('./images/mine/club2.png'),
    shanyaodeyanzhuzi: require('./images/mine/shanyaodeyanzhuzi.png'),
    shangchuan: require('./images/mine/lingcunwei.png'),
    peixunyixiang:require('./images/mine/peixunyixiang.png'),
    sex:require('./images/mine/sex.png'),
    intro:require('./images/mine/intro.png'),
    roleBack:require('./images/mine/roleBack.png'),
    about:require('./images/mine/about.png'),
    rewardBack:require('./images/mine/rewardBack.png'),
    roleHeader:require('./images/mine/roleHeader.png'),
    Subtract: require('./images/mine/Subtract.png'),
    jifenka: require('./images/mine/jifenka.png'),
    integralBack: require('./images/mine/integralBack.png'),
    jifenLeft: require('./images/mine/jifenLeft.png'),
    jifenRight: require('./images/mine/jifenRight.png'),
    rightArrow: require('./images/mine/right.png'),
    qiangzu: require('./images/mine/qiangzu.png'),
    laonianzu: require('./images/mine/laonianzu.png'),
    jifenDetails: require('./images/mine/jifenDetails.png'),
    zongjifen: require('./images/mine/zongjifen.png'),
    rule: require('./images/mine/rule.png'),
    ruleContent: require('./images/mine/ruleContent.png'),
    contestRight: require('./images/mine/contestRight.png'),
  },
  dynamic: {
    photo: require('./images/dynamic/photo.png'),
    video: require('./images/dynamic/video.png'),
  },
  back: require('./images/back.png'),
  startPage: require('./images/startPage.png'),




  //商城
  shoppingCar: require('./images/shopping/shoppingCar.png'),
  bchilun: require('./images/shopping/bchilun.png'),
  maozi :require('./images/shopping/maozi.png'),
  vipPrice :require('./images/shopping/vipPrice.png'),
  xuanze :require('./images/shopping/xuanze.png'),
  jiantou: require('./images/shopping/jiantou.png'),
  youfei :require('./images/shopping/youfei.png'),
  sftgfp: require('./images/shopping/sftgfp.png'),
  pingjia: require('./images/shopping/pingjia.png'),
  yellowStar: require('./images/shopping/yellow-star.png'),
  star: require('./images/shopping/star.png'),
  detail: require('./images/shopping/detail.png'),
  kefu: require('./images/shopping/kefu.png'),
  chilun: require('./images/shopping/chilun.png'),
  kongquan: require('./images/shopping/kongquan.png'),
  xiajiantou: require('./images/shopping/xiajiantou.png'),
  huijianhao: require('./images/shopping/jianhao.png'),
  heijianhao: require('./images/shopping/heijianhao.png'),
  jiahao: require('./images/shopping/jiahao.png'),
  yixiajia : require('./images/shopping/yixiajia.png'),
  wuhuo : require('./images/shopping/wuhuo.png'),
  hongduigou : require('./images/shopping/hongduigou.png'),
  qianbi : require('./images/shopping/qianbi.png'),
  lajitong : require('./images/shopping/lajitong.png'),
  cha : require('./images/shopping/cha.png'),
  dahengtiao: require('./images/shopping/dahengtiao.png'),
  giao: require('./images/shopping/giao.png'),
  meifapiao: require('./images/shopping/meifapiao.png'),
  daifukuan: require('./images/shopping/daifukuan.png'),
  daifahuo: require('./images/shopping/daifahuo.png'),
  daishouhuo: require('./images/shopping/daishouhuo.png'),
  daipingjia: require('./images/shopping/daipingjia.png'),
  shouhou: require('./images/shopping/shouhou.png'),
  dangandai: require('./images/shopping/dangandai.png'),
  dangandai2: require('./images/shopping/dangandai2.png'),
  shouliqian: require('./images/shopping/shouliqian.png'),
  erweima: require('./images/shopping/erweima.png'),
  dengpao: require('./images/shopping/dengpao.png'),
  shangchuan: require('./images/shopping/shangchuan.png'),
  shouhuoche: require('./images/shopping/shouhuoche.png'),
  xiaoche: require('./images/shopping/xiaoche.png'),
  redStar: require('./images/shopping/red-star.png'),
  querenshouhuo: require('./images/shopping/querenshouhuo.png'),
  dingdan: require('./images/shopping/dingdan.png'),
  shili: require('./images/shopping/shili.png'),
  dayoujiantou:require('./images/shopping/dayoujiantou.png'),
  fukuanshili:require('./images/shopping/fukuanshili.png'),

};
