import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  contactUsLabel: {
    marginHorizontal: 15,
    marginVertical: 10,
    fontSize: 18,
    color: 'gray',
  },
  itemValue: {
    flex: 1,
    borderRadius: scaleSize(8),
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  fontA: {
    fontSize: 16,
    color: '#8C9091',
  },
  fontB: {
    fontSize: 16,
    color: '#2B2B2B',
    marginHorizontal: 10,
    marginVertical: 5,
  },
  fontC: {
    fontSize: 16,
    color: '#2B2B2B',
    width: scaleSize(194),
    height: scaleSize(70),
    textAlign: 'right',
  },
  fontD: {
    fontSize: 16,
    color: '#8C9091',
    width: scaleSize(128),
    height: scaleSize(46),
    textAlign: 'left',
  },
  box1: {
    // width: '100%',
    height: scaleSize(62),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    backgroundColor: '#fff',
    paddingLeft: scaleSize(15),
    // paddingRight: scaleSize(15),
    borderWidth: scaleSize(1),
    borderColor: '#CCCCCC',
    marginHorizontal: 15,
  },
  box2: {
    // width: '100%',
    height: scaleSize(62),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    backgroundColor: '#fff',
    paddingLeft: scaleSize(15),
    // paddingRight: scaleSize(15),
    borderBottomWidth: scaleSize(1),
    borderLeftWidth: scaleSize(1),
    borderRightWidth: scaleSize(1),
    borderColor: '#CCCCCC',
    marginHorizontal: 15,
  },
  address: {
    // width: '100%',
    height: scaleSize(110),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    backgroundColor: '#fff',
    paddingLeft: scaleSize(15),
    // paddingRight: scaleSize(15),
    borderWidth: scaleSize(1),
    borderColor: '#CCCCCC',
    marginHorizontal: 15,
  },


});
