export const countries = [
    { display: false, name: "Afghanistan (‫افغانستان‬‎)", flag: require("../../res/images/flags/af.png"), code: "af", dialCode: "93" },
    { display: false, name: "Albania (Shqipëri)", flag: require("../../res/images/flags/al.png"), code: "al", dialCode: "355" },
    { display: false, name: "Algeria (‫الجزائر‬‎)", flag: require("../../res/images/flags/dz.png"), code: "dz", dialCode: "213" },
    { display: false, name: "American Samoa", flag: require("../../res/images/flags/as.png"), code: "as", dialCode: "1684" },
    { display: false, name: "Andorra", flag: require("../../res/images/flags/ad.png"), code: "ad", dialCode: "376" },
    { display: false, name: "Angola", flag: require("../../res/images/flags/ao.png"), code: "ao", dialCode: "244" },
    { display: false, name: "Anguilla", flag: require("../../res/images/flags/ai.png"), code: "ai", dialCode: "1264" },
    { display: false, name: "Antigua and Barbuda", flag: require("../../res/images/flags/ag.png"), code: "ag", dialCode: "1268" },
    { display: false, name: "Argentina", flag: require("../../res/images/flags/ar.png"), code: "ar", dialCode: "54" },
    { display: false, name: "Armenia (Հայաստան)", flag: require("../../res/images/flags/am.png"), code: "am", dialCode: "374" },
    { display: false, name: "Aruba", flag: require("../../res/images/flags/aw.png"), code: "aw", dialCode: "297" },
    { display: false, name: "Australia", flag: require("../../res/images/flags/au.png"), code: "au", dialCode: "61" },
    { display: false, name: "Austria (Österreich)", flag: require("../../res/images/flags/at.png"), code: "at", dialCode: "43" },
    { display: false, name: "Azerbaijan (Azərbaycan)", flag: require("../../res/images/flags/az.png"), code: "az", dialCode: "994" },
    { display: false, name: "Bahamas", flag: require("../../res/images/flags/bs.png"), code: "bs", dialCode: "1242" },
    { display: false, name: "Bahrain (‫البحرين‬‎)", flag: require("../../res/images/flags/bh.png"), code: "bh", dialCode: "973" },
    { display: false, name: "Bangladesh (বাংলাদেশ)", flag: require("../../res/images/flags/bd.png"), code: "bd", dialCode: "880" },
    { display: false, name: "Barbados", flag: require("../../res/images/flags/bb.png"), code: "bb", dialCode: "1246" },
    { display: false, name: "Belarus (Беларусь)", flag: require("../../res/images/flags/by.png"), code: "by", dialCode: "375" },
    { display: false, name: "Belgium (België)", flag: require("../../res/images/flags/be.png"), code: "be", dialCode: "32" },
    { display: false, name: "Belize", flag: require("../../res/images/flags/bz.png"), code: "bz", dialCode: "501" },
    { display: false, name: "Benin (Bénin)", flag: require("../../res/images/flags/bj.png"), code: "bj", dialCode: "229" },
    { display: false, name: "Bermuda", flag: require("../../res/images/flags/bm.png"), code: "bm", dialCode: "1441" },
    { display: false, name: "Bhutan (འབྲུག)", flag: require("../../res/images/flags/bt.png"), code: "bt", dialCode: "975" },
    { display: false, name: "Bolivia", flag: require("../../res/images/flags/bo.png"), code: "bo", dialCode: "591" },
    { display: false, name: "Bosnia and Herzegovina (Босна и Херцеговина)", flag: require("../../res/images/flags/ba.png"), code: "ba", dialCode: "387" },
    { display: false, name: "Botswana", flag: require("../../res/images/flags/bw.png"), code: "bw", dialCode: "267" },
    { display: false, name: "Brazil (Brasil)", flag: require("../../res/images/flags/br.png"), code: "br", dialCode: "55" },
    { display: false, name: "British Indian Ocean Territory", flag: require("../../res/images/flags/io.png"), code: "io", dialCode: "246" },
    { display: false, name: "British Virgin Islands", flag: require("../../res/images/flags/vg.png"), code: "vg", dialCode: "1284" },
    { display: false, name: "Brunei", flag: require("../../res/images/flags/bn.png"), code: "bn", dialCode: "673" },
    { display: false, name: "Bulgaria (България)", flag: require("../../res/images/flags/bg.png"), code: "bg", dialCode: "359" },
    { display: false, name: "Burkina Faso", flag: require("../../res/images/flags/bf.png"), code: "bf", dialCode: "226" },
    { display: false, name: "Burundi (Uburundi)", flag: require("../../res/images/flags/bi.png"), code: "bi", dialCode: "257" },
    { display: false, name: "Cambodia (កម្ពុជា)", flag: require("../../res/images/flags/kh.png"), code: "kh", dialCode: "855" },
    { display: false, name: "Cameroon (Cameroun)", flag: require("../../res/images/flags/cm.png"), code: "cm", dialCode: "237" },
    { display: false, name: "Canada", flag: require("../../res/images/flags/ca.png"), code: "ca", dialCode: "1" },
    { display: false, name: "Cape Verde (Kabu Verdi)", flag: require("../../res/images/flags/cv.png"), code: "cv", dialCode: "238" },
    { display: false, name: "Caribbean Netherlands", flag: require("../../res/images/flags/bq.png"), code: "bq", dialCode: "599" },
    { display: false, name: "Cayman Islands", flag: require("../../res/images/flags/ky.png"), code: "ky", dialCode: "1345" },
    { display: false, name: "Central African Republic (République centrafricaine)", flag: require("../../res/images/flags/cf.png"), code: "cf", dialCode: "236" },
    { display: false, name: "Chad (Tchad)", flag: require("../../res/images/flags/td.png"), code: "td", dialCode: "235" },
    { display: false, name: "Chile", flag: require("../../res/images/flags/cl.png"), code: "cl", dialCode: "56" },
    { display: true, name: "China (中国)", flag: require("../../res/images/flags/cn.png"), code: "cn", dialCode: "86" },
    { display: false, name: "China(Hong Kong) (中国香港地区)", flag: require("../../res/images/flags/hk.png"), code: "hk", dialCode: "852" },
    { display: false, name: "China(Macau) (中国澳門地区)", flag: require("../../res/images/flags/mo.png"), code: "mo", dialCode: "853" },
    { display: false, name: "China(Taiwan) (中国台灣地区)", flag: require("../../res/images/flags/tw.png"), code: "tw", dialCode: "886" },
    { display: false, name: "Christmas Island", flag: require("../../res/images/flags/cx.png"), code: "cx", dialCode: "61" },
    { display: false, name: "Cocos (Keeling) Islands", flag: require("../../res/images/flags/cc.png"), code: "cc", dialCode: "61" },
    { display: false, name: "Colombia", flag: require("../../res/images/flags/co.png"), code: "co", dialCode: "57" },
    { display: false, name: "Comoros (‫جزر القمر‬‎)", flag: require("../../res/images/flags/km.png"), code: "km", dialCode: "269" },
    { display: false, name: "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)", flag: require("../../res/images/flags/cd.png"), code: "cd", dialCode: "243" },
    { display: false, name: "Congo (Republic) (Congo-Brazzaville)", flag: require("../../res/images/flags/cg.png"), code: "cg", dialCode: "242" },
    { display: false, name: "Cook Islands", flag: require("../../res/images/flags/ck.png"), code: "ck", dialCode: "682" },
    { display: false, name: "Costa Rica", flag: require("../../res/images/flags/cr.png"), code: "cr", dialCode: "506" },
    { display: false, name: "Côte d’Ivoire", flag: require("../../res/images/flags/ci.png"), code: "ci", dialCode: "225" },
    { display: false, name: "Croatia (Hrvatska)", flag: require("../../res/images/flags/hr.png"), code: "hr", dialCode: "385" },
    { display: false, name: "Cuba", flag: require("../../res/images/flags/cu.png"), code: "cu", dialCode: "53" },
    { display: false, name: "Curaçao", flag: require("../../res/images/flags/cw.png"), code: "cw", dialCode: "599" },
    { display: false, name: "Cyprus (Κύπρος)", flag: require("../../res/images/flags/cy.png"), code: "cy", dialCode: "357" },
    { display: false, name: "Czech Republic (Česká republika)", flag: require("../../res/images/flags/cz.png"), code: "cz", dialCode: "420" },
    { display: false, name: "Denmark (Danmark)", flag: require("../../res/images/flags/dk.png"), code: "dk", dialCode: "45" },
    { display: false, name: "Djibouti", flag: require("../../res/images/flags/dj.png"), code: "dj", dialCode: "253" },
    { display: false, name: "Dominica", flag: require("../../res/images/flags/dm.png"), code: "dm", dialCode: "1767" },
    { display: false, name: "Dominican Republic (República Dominicana)", flag: require("../../res/images/flags/do.png"), code: "do", dialCode: "1" },
    { display: false, name: "Ecuador", flag: require("../../res/images/flags/ec.png"), code: "ec", dialCode: "593" },
    { display: false, name: "Egypt (‫مصر‬‎)", flag: require("../../res/images/flags/eg.png"), code: "eg", dialCode: "20" },
    { display: false, name: "El Salvador", flag: require("../../res/images/flags/sv.png"), code: "sv", dialCode: "503" },
    { display: false, name: "Equatorial Guinea (Guinea Ecuatorial)", flag: require("../../res/images/flags/gq.png"), code: "gq", dialCode: "240" },
    { display: false, name: "Eritrea", flag: require("../../res/images/flags/er.png"), code: "er", dialCode: "291" },
    { display: false, name: "Estonia (Eesti)", flag: require("../../res/images/flags/ee.png"), code: "ee", dialCode: "372" },
    { display: false, name: "Ethiopia", flag: require("../../res/images/flags/et.png"), code: "et", dialCode: "251" },
    { display: false, name: "Falkland Islands (Islas Malvinas)", flag: require("../../res/images/flags/fk.png"), code: "fk", dialCode: "500" },
    { display: false, name: "Faroe Islands (Føroyar)", flag: require("../../res/images/flags/fo.png"), code: "fo", dialCode: "298" },
    { display: false, name: "Fiji", flag: require("../../res/images/flags/fj.png"), code: "fj", dialCode: "679" },
    { display: false, name: "Finland (Suomi)", flag: require("../../res/images/flags/fi.png"), code: "fi", dialCode: "358" },
    { display: false, name: "France", flag: require("../../res/images/flags/fr.png"), code: "fr", dialCode: "33" },
    { display: false, name: "French Guiana (Guyane française)", flag: require("../../res/images/flags/gf.png"), code: "gf", dialCode: "594" },
    { display: false, name: "French Polynesia (Polynésie française)", flag: require("../../res/images/flags/pf.png"), code: "pf", dialCode: "689" },
    { display: false, name: "Gabon", flag: require("../../res/images/flags/ga.png"), code: "ga", dialCode: "241" },
    { display: false, name: "Gambia", flag: require("../../res/images/flags/gm.png"), code: "gm", dialCode: "220" },
    { display: false, name: "Georgia (საქართველო)", flag: require("../../res/images/flags/ge.png"), code: "ge", dialCode: "995" },
    { display: false, name: "Germany (Deutschland)", flag: require("../../res/images/flags/de.png"), code: "de", dialCode: "49" },
    { display: false, name: "Ghana (Gaana)", flag: require("../../res/images/flags/gh.png"), code: "gh", dialCode: "233" },
    { display: false, name: "Gibraltar", flag: require("../../res/images/flags/gi.png"), code: "gi", dialCode: "350" },
    { display: false, name: "Greece (Ελλάδα)", flag: require("../../res/images/flags/gr.png"), code: "gr", dialCode: "30" },
    { display: false, name: "Greenland (Kalaallit Nunaat)", flag: require("../../res/images/flags/gl.png"), code: "gl", dialCode: "299" },
    { display: false, name: "Grenada", flag: require("../../res/images/flags/gd.png"), code: "gd", dialCode: "1473" },
    { display: false, name: "Guadeloupe", flag: require("../../res/images/flags/gp.png"), code: "gp", dialCode: "590" },
    { display: false, name: "Guam", flag: require("../../res/images/flags/gu.png"), code: "gu", dialCode: "1671" },
    { display: false, name: "Guatemala", flag: require("../../res/images/flags/gt.png"), code: "gt", dialCode: "502" },
    { display: false, name: "Guernsey", flag: require("../../res/images/flags/gg.png"), code: "gg", dialCode: "44" },
    { display: false, name: "Guinea (Guinée)", flag: require("../../res/images/flags/gn.png"), code: "gn", dialCode: "224" },
    { display: false, name: "Guinea-Bissau (Guiné Bissau)", flag: require("../../res/images/flags/gw.png"), code: "gw", dialCode: "245" },
    { display: false, name: "Guyana", flag: require("../../res/images/flags/gy.png"), code: "gy", dialCode: "592" },
    { display: false, name: "Haiti", flag: require("../../res/images/flags/ht.png"), code: "ht", dialCode: "509" },
    { display: false, name: "Honduras", flag: require("../../res/images/flags/hn.png"), code: "hn", dialCode: "504" },
    { display: false, name: "Hungary (Magyarország)", flag: require("../../res/images/flags/hu.png"), code: "hu", dialCode: "36" },
    { display: false, name: "Iceland (Ísland)", flag: require("../../res/images/flags/is.png"), code: "is", dialCode: "354" },
    { display: false, name: "India (भारत)", flag: require("../../res/images/flags/in.png"), code: "in", dialCode: "91" },
    { display: false, name: "Indonesia", flag: require("../../res/images/flags/id.png"), code: "id", dialCode: "62" },
    { display: false, name: "Iran (‫ایران‬‎)", flag: require("../../res/images/flags/ir.png"), code: "ir", dialCode: "98" },
    { display: false, name: "Iraq (‫العراق‬‎)", flag: require("../../res/images/flags/iq.png"), code: "iq", dialCode: "964" },
    { display: false, name: "Ireland", flag: require("../../res/images/flags/ie.png"), code: "ie", dialCode: "353" },
    { display: false, name: "Isle of Man", flag: require("../../res/images/flags/im.png"), code: "im", dialCode: "44" },
    { display: false, name: "Israel (‫ישראל‬‎)", flag: require("../../res/images/flags/il.png"), code: "il", dialCode: "972" },
    { display: false, name: "Italy (Italia)", flag: require("../../res/images/flags/it.png"), code: "it", dialCode: "39" },
    { display: false, name: "Jamaica", flag: require("../../res/images/flags/jm.png"), code: "jm", dialCode: "1876" },
    { display: false, name: "Japan (日本)", flag: require("../../res/images/flags/jp.png"), code: "jp", dialCode: "81" },
    { display: false, name: "Jersey", flag: require("../../res/images/flags/je.png"), code: "je", dialCode: "44" },
    { display: false, name: "Jordan (‫الأردن‬‎)", flag: require("../../res/images/flags/jo.png"), code: "jo", dialCode: "962" },
    { display: false, name: "Kazakhstan (Казахстан)", flag: require("../../res/images/flags/kz.png"), code: "kz", dialCode: "77" },
    { display: true, name: "Kenya", flag: require("../../res/images/flags/ke.png"), code: "ke", dialCode: "254" },
    { display: false, name: "Kiribati", flag: require("../../res/images/flags/ki.png"), code: "ki", dialCode: "686" },
    { display: false, name: "Kuwait (‫الكويت‬‎)", flag: require("../../res/images/flags/kw.png"), code: "kw", dialCode: "965" },
    { display: false, name: "Kyrgyzstan (Кыргызстан)", flag: require("../../res/images/flags/kg.png"), code: "kg", dialCode: "996" },
    { display: false, name: "Laos (ລາວ)", flag: require("../../res/images/flags/la.png"), code: "la", dialCode: "856" },
    { display: false, name: "Latvia (Latvija)", flag: require("../../res/images/flags/lv.png"), code: "lv", dialCode: "371" },
    { display: false, name: "Lebanon (‫لبنان‬‎)", flag: require("../../res/images/flags/lb.png"), code: "lb", dialCode: "961" },
    { display: false, name: "Lesotho", flag: require("../../res/images/flags/ls.png"), code: "ls", dialCode: "266" },
    { display: false, name: "Liberia", flag: require("../../res/images/flags/lr.png"), code: "lr", dialCode: "231" },
    { display: false, name: "Libya (‫ليبيا‬‎)", flag: require("../../res/images/flags/ly.png"), code: "ly", dialCode: "218" },
    { display: false, name: "Liechtenstein", flag: require("../../res/images/flags/li.png"), code: "li", dialCode: "423" },
    { display: false, name: "Lithuania (Lietuva)", flag: require("../../res/images/flags/lt.png"), code: "lt", dialCode: "370" },
    { display: false, name: "Luxembourg", flag: require("../../res/images/flags/lu.png"), code: "lu", dialCode: "352" },
    { display: false, name: "Macedonia (FYROM) (Македонија)", flag: require("../../res/images/flags/mk.png"), code: "mk", dialCode: "389" },
    { display: false, name: "Madagascar (Madagasikara)", flag: require("../../res/images/flags/mg.png"), code: "mg", dialCode: "261" },
    { display: false, name: "Malawi", flag: require("../../res/images/flags/mw.png"), code: "mw", dialCode: "265" },
    { display: false, name: "Malaysia", flag: require("../../res/images/flags/my.png"), code: "my", dialCode: "60" },
    { display: false, name: "Maldives", flag: require("../../res/images/flags/mv.png"), code: "mv", dialCode: "960" },
    { display: false, name: "Mali", flag: require("../../res/images/flags/ml.png"), code: "ml", dialCode: "223" },
    { display: false, name: "Malta", flag: require("../../res/images/flags/mt.png"), code: "mt", dialCode: "356" },
    { display: false, name: "Marshall Islands", flag: require("../../res/images/flags/mh.png"), code: "mh", dialCode: "692" },
    { display: false, name: "Martinique", flag: require("../../res/images/flags/mq.png"), code: "mq", dialCode: "596" },
    { display: false, name: "Mauritania (‫موريتانيا‬‎)", flag: require("../../res/images/flags/mr.png"), code: "mr", dialCode: "222" },
    { display: false, name: "Mauritius (Moris)", flag: require("../../res/images/flags/mu.png"), code: "mu", dialCode: "230" },
    { display: false, name: "Mayotte", flag: require("../../res/images/flags/yt.png"), code: "yt", dialCode: "262" },
    { display: false, name: "Mexico (México)", flag: require("../../res/images/flags/mx.png"), code: "mx", dialCode: "52" },
    { display: false, name: "Micronesia", flag: require("../../res/images/flags/fm.png"), code: "fm", dialCode: "691" },
    { display: false, name: "Moldova (Republica Moldova)", flag: require("../../res/images/flags/md.png"), code: "md", dialCode: "373" },
    { display: false, name: "Monaco", flag: require("../../res/images/flags/mc.png"), code: "mc", dialCode: "377" },
    { display: false, name: "Mongolia (Монгол)", flag: require("../../res/images/flags/mn.png"), code: "mn", dialCode: "976" },
    { display: false, name: "Montenegro (Crna Gora)", flag: require("../../res/images/flags/me.png"), code: "me", dialCode: "382" },
    { display: false, name: "Montserrat", flag: require("../../res/images/flags/ms.png"), code: "ms", dialCode: "1664" },
    { display: false, name: "Morocco (‫المغرب‬‎)", flag: require("../../res/images/flags/ma.png"), code: "ma", dialCode: "212" },
    { display: false, name: "Mozambique (Moçambique)", flag: require("../../res/images/flags/mz.png"), code: "mz", dialCode: "258" },
    { display: false, name: "Myanmar (Burma)", flag: require("../../res/images/flags/mm.png"), code: "mm", dialCode: "95" },
    { display: false, name: "Namibia (Namibië)", flag: require("../../res/images/flags/na.png"), code: "na", dialCode: "264" },
    { display: false, name: "Nauru", flag: require("../../res/images/flags/nr.png"), code: "nr", dialCode: "674" },
    { display: false, name: "Nepal (नेपाल)", flag: require("../../res/images/flags/np.png"), code: "np", dialCode: "977" },
    { display: false, name: "Netherlands (Nederland)", flag: require("../../res/images/flags/nl.png"), code: "nl", dialCode: "31" },
    { display: false, name: "New Caledonia (Nouvelle-Calédonie)", flag: require("../../res/images/flags/nc.png"), code: "nc", dialCode: "687" },
    { display: false, name: "New Zealand", flag: require("../../res/images/flags/nz.png"), code: "nz", dialCode: "64" },
    { display: false, name: "Nicaragua", flag: require("../../res/images/flags/ni.png"), code: "ni", dialCode: "505" },
    { display: false, name: "Niger (Nijar)", flag: require("../../res/images/flags/ne.png"), code: "ne", dialCode: "227" },
    { display: false, name: "Nigeria", flag: require("../../res/images/flags/ng.png"), code: "ng", dialCode: "234" },
    { display: false, name: "Niue", flag: require("../../res/images/flags/nu.png"), code: "nu", dialCode: "683" },
    { display: false, name: "Norfolk Island", flag: require("../../res/images/flags/nf.png"), code: "nf", dialCode: "672" },
    { display: false, name: "North Korea (조선 민주주의 인민 공화국)", flag: require("../../res/images/flags/kp.png"), code: "kp", dialCode: "850" },
    { display: false, name: "Northern Mariana Islands", flag: require("../../res/images/flags/mp.png"), code: "mp", dialCode: "1670" },
    { display: false, name: "Norway (Norge)", flag: require("../../res/images/flags/no.png"), code: "no", dialCode: "47" },
    { display: false, name: "Oman (‫عُمان‬‎)", flag: require("../../res/images/flags/om.png"), code: "om", dialCode: "968" },
    { display: false, name: "Pakistan (‫پاکستان‬‎)", flag: require("../../res/images/flags/pk.png"), code: "pk", dialCode: "92" },
    { display: false, name: "Palau", flag: require("../../res/images/flags/pw.png"), code: "pw", dialCode: "680" },
    { display: false, name: "Palestine (‫فلسطين‬‎)", flag: require("../../res/images/flags/ps.png"), code: "ps", dialCode: "970" },
    { display: false, name: "Panama (Panamá)", flag: require("../../res/images/flags/pa.png"), code: "pa", dialCode: "507" },
    { display: false, name: "Papua New Guinea", flag: require("../../res/images/flags/pg.png"), code: "pg", dialCode: "675" },
    { display: false, name: "Paraguay", flag: require("../../res/images/flags/py.png"), code: "py", dialCode: "595" },
    { display: false, name: "Peru (Perú)", flag: require("../../res/images/flags/pe.png"), code: "pe", dialCode: "51" },
    { display: false, name: "Philippines", flag: require("../../res/images/flags/ph.png"), code: "ph", dialCode: "63" },
    { display: false, name: "Poland (Polska)", flag: require("../../res/images/flags/pl.png"), code: "pl", dialCode: "48" },
    { display: false, name: "Portugal", flag: require("../../res/images/flags/pt.png"), code: "pt", dialCode: "351" },
    { display: false, name: "Puerto Rico", flag: require("../../res/images/flags/pr.png"), code: "pr", dialCode: "1" },
    { display: false, name: "Qatar (‫قطر‬‎)", flag: require("../../res/images/flags/qa.png"), code: "qa", dialCode: "974" },
    { display: false, name: "Réunion (La Réunion)", flag: require("../../res/images/flags/re.png"), code: "re", dialCode: "262" },
    { display: false, name: "Romania (România)", flag: require("../../res/images/flags/ro.png"), code: "ro", dialCode: "40" },
    { display: false, name: "Russia (Россия)", flag: require("../../res/images/flags/ru.png"), code: "ru", dialCode: "7" },
    { display: false, name: "Rwanda", flag: require("../../res/images/flags/rw.png"), code: "rw", dialCode: "250" },
    { display: false, name: "Saint Barthélemy (Saint-Barthélemy)", flag: require("../../res/images/flags/bl.png"), code: "bl", dialCode: "590" },
    { display: false, name: "Saint Helena", flag: require("../../res/images/flags/sh.png"), code: "sh", dialCode: "290" },
    { display: false, name: "Saint Kitts and Nevis", flag: require("../../res/images/flags/kn.png"), code: "kn", dialCode: "1869" },
    { display: false, name: "Saint Lucia", flag: require("../../res/images/flags/lc.png"), code: "lc", dialCode: "1758" },
    { display: false, name: "Saint Martin (Saint-Martin (partie française))", flag: require("../../res/images/flags/mf.png"), code: "mf", dialCode: "590" },
    { display: false, name: "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)", flag: require("../../res/images/flags/pm.png"), code: "pm", dialCode: "508" },
    { display: false, name: "Saint Vincent and the Grenadines", flag: require("../../res/images/flags/vc.png"), code: "vc", dialCode: "1784" },
    { display: false, name: "Samoa", flag: require("../../res/images/flags/ws.png"), code: "ws", dialCode: "685" },
    { display: false, name: "San Marino", flag: require("../../res/images/flags/sm.png"), code: "sm", dialCode: "378" },
    { display: false, name: "São Tomé and Príncipe (São Tomé e Príncipe)", flag: require("../../res/images/flags/st.png"), code: "st", dialCode: "239" },
    { display: false, name: "Saudi Arabia (‫المملكة العربية السعودية‬‎)", flag: require("../../res/images/flags/sa.png"), code: "sa", dialCode: "966" },
    { display: false, name: "Senegal (Sénégal)", flag: require("../../res/images/flags/sn.png"), code: "sn", dialCode: "221" },
    { display: false, name: "Serbia (Србија)", flag: require("../../res/images/flags/rs.png"), code: "rs", dialCode: "381" },
    { display: false, name: "Seychelles", flag: require("../../res/images/flags/sc.png"), code: "sc", dialCode: "248" },
    { display: false, name: "Sierra Leone", flag: require("../../res/images/flags/sl.png"), code: "sl", dialCode: "232" },
    { display: false, name: "Singapore", flag: require("../../res/images/flags/sg.png"), code: "sg", dialCode: "65" },
    { display: false, name: "Sint Maarten", flag: require("../../res/images/flags/sx.png"), code: "sx", dialCode: "1721" },
    { display: false, name: "Slovakia (Slovensko)", flag: require("../../res/images/flags/sk.png"), code: "sk", dialCode: "421" },
    { display: false, name: "Slovenia (Slovenija)", flag: require("../../res/images/flags/si.png"), code: "si", dialCode: "386" },
    { display: false, name: "Solomon Islands", flag: require("../../res/images/flags/sb.png"), code: "sb", dialCode: "677" },
    { display: false, name: "Somalia (Soomaaliya)", flag: require("../../res/images/flags/so.png"), code: "so", dialCode: "252" },
    { display: false, name: "South Africa", flag: require("../../res/images/flags/za.png"), code: "za", dialCode: "27" },
    { display: false, name: "South Korea (대한민국)", flag: require("../../res/images/flags/kr.png"), code: "kr", dialCode: "82" },
    { display: false, name: "South Sudan (‫جنوب السودان‬‎)", flag: require("../../res/images/flags/ss.png"), code: "ss", dialCode: "211" },
    { display: false, name: "Spain (España)", flag: require("../../res/images/flags/es.png"), code: "es", dialCode: "34" },
    { display: false, name: "Sri Lanka (ශ්‍රී ලංකාව)", flag: require("../../res/images/flags/lk.png"), code: "lk", dialCode: "94" },
    { display: false, name: "Sudan (‫السودان‬‎)", flag: require("../../res/images/flags/sd.png"), code: "sd", dialCode: "249" },
    { display: false, name: "Suriname", flag: require("../../res/images/flags/sr.png"), code: "sr", dialCode: "597" },
    { display: false, name: "Svalbard and Jan Mayen", flag: require("../../res/images/flags/sj.png"), code: "sj", dialCode: "47" },
    { display: false, name: "Swaziland", flag: require("../../res/images/flags/sz.png"), code: "sz", dialCode: "268" },
    { display: false, name: "Sweden (Sverige)", flag: require("../../res/images/flags/se.png"), code: "se", dialCode: "46" },
    { display: false, name: "Switzerland (Schweiz)", flag: require("../../res/images/flags/ch.png"), code: "ch", dialCode: "41" },
    { display: false, name: "Syria (‫سوريا‬‎)", flag: require("../../res/images/flags/sy.png"), code: "sy", dialCode: "963" },
    { display: false, name: "Tajikistan", flag: require("../../res/images/flags/tj.png"), code: "tj", dialCode: "992" },
    { display: false, name: "Tanzania", flag: require("../../res/images/flags/tz.png"), code: "tz", dialCode: "255" },
    { display: false, name: "Thailand (ไทย)", flag: require("../../res/images/flags/th.png"), code: "th", dialCode: "66" },
    { display: false, name: "Timor-Leste", flag: require("../../res/images/flags/tl.png"), code: "tl", dialCode: "670" },
    { display: false, name: "Togo", flag: require("../../res/images/flags/tg.png"), code: "tg", dialCode: "228" },
    { display: false, name: "Tokelau", flag: require("../../res/images/flags/tk.png"), code: "tk", dialCode: "690" },
    { display: false, name: "Tonga", flag: require("../../res/images/flags/to.png"), code: "to", dialCode: "676" },
    { display: false, name: "Trinidad and Tobago", flag: require("../../res/images/flags/tt.png"), code: "tt", dialCode: "1868" },
    { display: false, name: "Tunisia (‫تونس‬‎)", flag: require("../../res/images/flags/tn.png"), code: "tn", dialCode: "216" },
    { display: false, name: "Turkey (Türkiye)", flag: require("../../res/images/flags/tr.png"), code: "tr", dialCode: "90" },
    { display: false, name: "Turkmenistan", flag: require("../../res/images/flags/tm.png"), code: "tm", dialCode: "993" },
    { display: false, name: "Turks and Caicos Islands", flag: require("../../res/images/flags/tc.png"), code: "tc", dialCode: "1649" },
    { display: false, name: "Tuvalu", flag: require("../../res/images/flags/tv.png"), code: "tv", dialCode: "688" },
    { display: false, name: "U.S. Virgin Islands", flag: require("../../res/images/flags/vi.png"), code: "vi", dialCode: "1340" },
    { display: false, name: "Uganda", flag: require("../../res/images/flags/ug.png"), code: "ug", dialCode: "256" },
    { display: false, name: "Ukraine (Україна)", flag: require("../../res/images/flags/ua.png"), code: "ua", dialCode: "380" },
    { display: false, name: "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)", flag: require("../../res/images/flags/ae.png"), code: "ae", dialCode: "971" },
    { display: false, name: "United Kingdom", flag: require("../../res/images/flags/gb.png"), code: "gb", dialCode: "44" },
    { display: true, name: "United States", flag: require("../../res/images/flags/us.png"), code: "us", dialCode: "1" },
    { display: false, name: "Uruguay", flag: require("../../res/images/flags/uy.png"), code: "uy", dialCode: "598" },
    { display: false, name: "Uzbekistan (Oʻzbekiston)", flag: require("../../res/images/flags/uz.png"), code: "uz", dialCode: "998" },
    { display: false, name: "Vanuatu", flag: require("../../res/images/flags/vu.png"), code: "vu", dialCode: "678" },
    { display: false, name: "Vatican City (Città del Vaticano)", flag: require("../../res/images/flags/va.png"), code: "va", dialCode: "39" },
    { display: false, name: "Venezuela", flag: require("../../res/images/flags/ve.png"), code: "ve", dialCode: "58" },
    { display: false, name: "Vietnam (Việt Nam)", flag: require("../../res/images/flags/vn.png"), code: "vn", dialCode: "84" },
    { display: false, name: "Wallis and Futuna", flag: require("../../res/images/flags/wf.png"), code: "wf", dialCode: "681" },
    { display: false, name: "Western Sahara (‫الصحراء الغربية‬‎)", flag: require("../../res/images/flags/eh.png"), code: "eh", dialCode: "212" },
    { display: false, name: "Yemen (‫اليمن‬‎)", flag: require("../../res/images/flags/ye.png"), code: "ye", dialCode: "967" },
    { display: false, name: "Zambia", flag: require("../../res/images/flags/zm.png"), code: "zm", dialCode: "260" },
    { display: false, name: "Zimbabwe", flag: require("../../res/images/flags/zw.png"), code: "zw", dialCode: "263" },
    { display: false, name: "Åland Islands", flag: require("../../res/images/flags/ax.png"), code: "ax", dialCode: "358" }
]